// components/shared/Newsletter/Newsletter.tsx
import { FormEvent, useRef, useState } from 'react'
import Confetti from 'react-dom-confetti'

import { CustomLink } from '@/root/components/shared/CustomLink'

export function Newsletter({ ...props }) {
  const [isSubscribed, setIsSubscribed] = useState<boolean>(false)
  const [isError, setIsError] = useState<boolean>(false)
  const inputEl = useRef<HTMLInputElement>(null)

  async function subscribe(event: FormEvent<HTMLFormElement>): Promise<void> {
    event.preventDefault()

    const response = await fetch('/api/newsletter', {
      body: JSON.stringify({
        email: inputEl?.current?.value,
      }),
      headers: {
        'Content-Type': 'application/json',
      },
      method: 'POST',
    })

    const { error } = await response.json()

    if (error) {
      setIsError(true)
      return
    }

    if (inputEl.current) {
      inputEl.current.value = ''
      setIsSubscribed(true)
      setTimeout(() => setIsSubscribed(false), 4000)
    }
  }

  return (
    <div className="p-8 rounded-md bg-highlight" {...props}>
      <div>
        <span className="text-xl font-bold text-secondary md:text-4xl">
          {'📬'} Subscribe for Updates
        </span>
        <p className="my-4 text-secondary">
          I don't want your data, so there's also a
          <CustomLink href="/feed/rss.xml">
            {' '}
            <span className="underline">RSS feed.</span>
          </CustomLink>
        </p>
      </div>

      <form className="mt-8" onSubmit={subscribe}>
        <input
          ref={inputEl}
          aria-label="Email for newsletter"
          className="max-w-[140px] sm:max-w-none p-2 text-highlight rounded-tl rounded-bl md:p-4 bg-secondary"
          id="newsletter-email"
          name="newsletter-email"
          placeholder="unix@chad.com"
          required
          type="email"
        />
        <button
          className="p-2 font-bold border-0 rounded-tr rounded-br shadow-sm md:p-4 bg-primary text-highlight"
          type="submit"
        >
          {!isError && !isSubscribed && 'Subscribe'}
          {isError && '💩 Try again'}
          {isSubscribed && 'Subscribed! 🎉'}
          <Confetti active={isSubscribed} />
        </button>
      </form>
    </div>
  )
}

// src/lib/ui/newsletter.svelte
<script lang="ts">
	import { fade } from 'svelte/transition'
	import { Envelope } from '$lib/icons'

	let email = $state('')
	let error = $state('')
	let success = $state('')

	async function onsubmit(e: SubmitEvent) {
		e.preventDefault()

		const response = await fetch('/api/subscribe', {
			method: 'post',
			body: JSON.stringify(email),
			headers: { 'Content-Type': 'application/json' },
		})
		const subscribe = await response.json()

		if (subscribe.error) {
			success = ''
			error = subscribe.error
		}

		if (subscribe.success) {
			error = ''
			success = subscribe.success
		}
	}
</script>

<form {onsubmit}>
	<label for="email" class="sr-only">Enter your email</label>
	<input
		bind:value={email}
		type="email"
		id="email"
		name="email"
		placeholder="giga@chad.com"
		autocomplete="on"
	/>
	<button type="submit">
		<Envelope width={24} height={24} aria-hidden={true} />
		<span>Subscribe</span>
	</button>
</form>

<div class="message">
	{#if error}
		<span in:fade class="error">{error}</span>
	{/if}

	{#if success}
		<span in:fade class="success">{success}</span>
	{/if}
</div>

<style>
	form {
		display: flex;
		max-width: 360px;
		height: 48px;
		margin: var(--spacing-16) 0;
		border-radius: var(--rounded-4);
		border: 1px solid var(--clr-input-border);
		box-shadow: var(--shadow-sm);

		input {
			width: 100%;
			padding: var(--spacing-8) var(--spacing-16);
			background-color: var(--clr-input-bg);
			border-radius: var(--rounded-4) 0 0 var(--rounded-4);
			flex: 1;

			&::placeholder {
				color: var(--clr-input-placeholder-txt);
			}
		}

		button {
			padding: var(--spacing-8);
			color: var(--clr-input-txt);
			background-color: var(--clr-primary);
			font-weight: 700;
			border-radius: 0 var(--rounded-4) var(--rounded-4) 0;

			@media (width >= 860px) {
				display: flex;
				align-items: center;
				gap: var(--spacing-4);
			}

			:global(svg) {
				display: none;

				@media (width >= 860px) {
					display: block;
				}
			}
		}
	}

	.message {
		margin-bottom: var(--spacing-16);
		font-weight: 700;

		.error {
			color: hsl(9 100% 64%);
		}

		.success {
			color: var(--clr-primary);
		}
	}
</style>
